# Generated by Django 2.1 on 2018-08-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_patient', '0012_auto_20180810_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiologue',
            name='tempsDeTravail',
            field=models.CharField(choices=[('1/2 temps', '1/2 temps'), ('3/4 temps', '3/4 temps'), ('temps complet', 'temps complet')], max_length=30, null=True),
        ),
    ]
