# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-17 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_patient', '0015_absence'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiologue',
            name='jourSansTravail',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='radiologue',
            name='vacationFixe',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
